stages:
  - test

variables:
  BUNDLE_PATH: "vendor/bundle"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - vendor/bundle/

rspec-tests:
  stage: test
  image: ruby:3.4

  before_script:
    - gem install bundler -v 2.6.9
    - bundle install

  script:
    - bundle exec rspec --format progress --format RspecJunitFormatter --out rspec.xml

  artifacts:
    when: always
    reports:
      junit: rspec.xml
    paths:
      - rspec.xml
    expire_in: 7 days
